services:
  umono:
    build:
      context: ./umono
      dockerfile: Dockerfile
    volumes:
      - ./umono.db:/usr/src/app/umono.db
      - ./.env:/usr/src/app/.env
    ports:
      - "8999:8999"
    networks:
      - umono-network

  admin-ui:
    build:
      context: ./admin-ui
      dockerfile: Dockerfile
    networks:
      - umono-network
    container_name: admin-ui

networks:
  umono-network:
    driver: bridge
